# Default values for empfinchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

pa:
  name: web
image:
  pullPolicy: IfNotPresent
  repository: registry.kingdonb.dev/admin/personnel-actions
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2.4.01"
service:
  type: ClusterIP
  port: 80
secretName: personnel-actions

replicaCount: 1

hrpy:
  name: hrpy
  replicaCount: 1
  image:
    repository: registry.kingdonb.dev/admin/hrpy-api
    tag: "v1.7.03"
  service:
    type: ClusterIP
    port: 80
  secretName: hrpy-api
person:
  name: person
  replicaCount: 1
  image:
    repository: registry.kingdonb.dev/admin/person-api
    tag: "v1.2.03"
  service:
    type: ClusterIP
    port: 80
  secretName: person-api
finance:
  name: finance
  replicaCount: 1
  image:
    repository: registry.kingdonb.dev/admin/finance-api
    tag: "v3.2.04"
  service:
    type: ClusterIP
    port: 80
  secretName: finance-api
faculty:
  name: faculty
  replicaCount: 1
  image:
    repository: registry.kingdonb.dev/admin/faculty-api
    tag: "v1.9.5.1"
  service:
    type: ClusterIP
    port: 80
  secretName: faculty-api
facilities:
  name: facilities
  replicaCount: 1
  image:
    repository: registry.kingdonb.dev/admin/facilities-api
    tag: "v1.2.1"
  service:
    type: ClusterIP
    port: 80
  secretName: facilities-api


imagePullSecrets: []
nameOverride: "empfin"
fullnameOverride: "personnel-actions"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: pa-project-dev.kingdonb.dev
      paths:
        - /
  tls:
   - secretName: pa-project-dev
     hosts:
       - pa-project-dev.kingdonb.dev

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
