apiVersion: v1
kind: Service
metadata:
  name: {{ include "empfinchart.fullname" . }}-facilities
  labels:
    {{- include "empfinchart.facilities.labels" . | nindent 4 }}
spec:
  type: {{ .Values.facilities.service.type }}
  ports:
    - port: {{ .Values.facilities.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "empfinchart.facilities.matchLabels" . | nindent 4 }}
