apiVersion: v1
kind: Service
metadata:
  name: {{ include "empfinchart.fullname" . }}-faculty
  labels:
    {{- include "empfinchart.faculty.labels" . | nindent 4 }}
spec:
  type: {{ .Values.faculty.service.type }}
  ports:
    - port: {{ .Values.faculty.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "empfinchart.faculty.matchLabels" . | nindent 4 }}
