{{- if .Values.health.ingress.enabled -}}
{{- $fullName := printf "%s-%s" (include "empfinchart.fullname" .) "health" -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "empfinchart.health.labels" . | nindent 4 }}
  {{- with .Values.health.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.health.ingress.tls }}
  tls:
    {{- range .Values.health.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.health.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: personnel-actions-health
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
