apiVersion: v1
kind: Service
metadata:
  name: {{ include "empfinchart.fullname" . }}-health
  labels:
    {{- include "empfinchart.health.labels" . | nindent 4 }}
spec:
  type: {{ .Values.health.service.type }}
  ports:
    - port: {{ .Values.health.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "empfinchart.health.matchLabels" . | nindent 4 }}
