apiVersion: v1
kind: Service
metadata:
  name: {{ include "empfinchart.fullname" . }}-hrpy
  labels:
    {{- include "empfinchart.hrpy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hrpy.service.type }}
  ports:
    - port: {{ .Values.hrpy.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "empfinchart.hrpy.matchLabels" . | nindent 4 }}
