apiVersion: v1
kind: Service
metadata:
  name: {{ include "empfinchart.fullname" . }}-person
  labels:
    {{- include "empfinchart.person.labels" . | nindent 4 }}
spec:
  type: {{ .Values.person.service.type }}
  ports:
    - port: {{ .Values.person.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "empfinchart.person.selectorLabels" . | nindent 4 }}
