{{- if .Values.canary.enabled }}
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ template "empfinchart.fullname" . }}
  labels:
    helm.sh/chart: {{ template "empfinchart.chart" . }}
    app.kubernetes.io/name: {{ template "empfinchart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  {{ template "empfinchart.fullname" . }}-web
  ingressRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: {{ template "empfinchart.fullname" . }}-web
  service:
    port: {{ .Values.service.port }}
    targetPort: 3000
  analysis:
    interval: {{ .Values.canary.analysis.interval }}
    threshold: {{ .Values.canary.analysis.threshold }}
    maxWeight: {{ .Values.canary.analysis.maxWeight }}
    stepWeight: {{ .Values.canary.analysis.stepWeight }}
    metrics:
    - name: request-success-rate
      threshold: {{ .Values.canary.thresholds.successRate }}
      interval: 1m
    - name: request-duration
      threshold: {{ .Values.canary.thresholds.latency }}
      interval: 1m
    webhooks: {{ if and (not .Values.canary.helmtest.enabled) (not .Values.canary.loadtest.enabled) }}{}{{ end }}
      {{- if .Values.canary.helmtest.enabled }}
      - name: "helm test"
        type: pre-rollout
        url: {{ .Values.canary.helmtest.url }}
        timeout: 3m
        metadata:
          type: "helmv3"
          cmd: "test {{ .Release.Name }} -n {{ .Release.Namespace }}"
      {{- end }}
      {{- if .Values.canary.loadtest.enabled }}
      - name: load-test-get
        url: {{ .Values.canary.loadtest.url }}
        timeout: 5s
        metadata:
          cmd: "hey -z 1m -q 5 -c 2 http://{{ template "empfinchart.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}"
      {{- end }}
{{- end }}
