apiVersion: v1
kind: Service
metadata:
  name: {{ include "empfinchart.fullname" . }}-web
  labels:
    {{- include "empfinchart.pa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pa.service.type }}
  ports:
    - port: {{ .Values.pa.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "empfinchart.pa.matchLabels" . | nindent 4 }}
